# Generated by Django 6.1.1 on 2026-09-11 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lojas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mecanica', models.CharField(choices=[('leve3', 'Leve 3 Pague 2'), ('supracorp', 'Degustação Supra Corp Day'), ('kenvue', 'Ofertas Kenvue'), ('principia', 'Ofertas Principia'), ('botica', 'Ofertas Botica'), ('procter', 'Ofertas Procter'), ('kimberly', 'Ofertas Kimberly'), ('cestoes', 'Cestões'), ('marketing', 'Itens do Marketing')], max_length=20, verbose_name='mecânica')),
                ('produto_descricao', models.CharField(max_length=255, verbose_name='produto')),
                ('produto_codigo_barras', models.CharField(blank=True, max_length=20, verbose_name='código de barras')),
                ('fabricante', models.CharField(blank=True, max_length=120, verbose_name='fabricante')),
                ('tag_origem', models.CharField(blank=True, help_text='Texto bruto de "Cad. Oferta"/"Detalhe Desconto", pra auditoria.', max_length=255, verbose_name='tag de origem')),
                ('grupo', models.CharField(blank=True, choices=[('base', 'Base (sem desconto)'), ('oferta', 'Oferta')], help_text='Só usado nas mecânicas de fabricante (base vs. oferta).', max_length=10, verbose_name='grupo')),
                ('ano_mes', models.CharField(help_text='formato AAAA-MM', max_length=7, verbose_name='ano-mês')),
                ('data', models.DateField(blank=True, help_text='só em relatórios diários', null=True, verbose_name='data')),
                ('itens', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='itens')),
                ('venda', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='venda')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='desconto')),
                ('custo', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='custo')),
                ('lucro', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='lucro')),
                ('arquivo_origem', models.CharField(blank=True, max_length=255, verbose_name='arquivo de origem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='lojas.loja')),
            ],
            options={
                'verbose_name': 'lançamento',
                'verbose_name_plural': 'lançamentos',
                'indexes': [models.Index(fields=['mecanica', 'ano_mes'], name='ofertas_lan_mecanic_919594_idx'), models.Index(fields=['mecanica', 'loja'], name='ofertas_lan_mecanic_ecb832_idx')],
            },
        ),
    ]
