# Generated by Django 6.1.1 on 2026-09-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='grupo',
            field=models.CharField(blank=True, choices=[('base', 'Base (sem desconto)'), ('oferta', 'Oferta')], help_text='Só usado nas ofertas de fabricante (base vs. oferta).', max_length=10, verbose_name='grupo'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='mecanica',
            field=models.CharField(choices=[('leve3', 'Leve 3 Pague 2'), ('supracorp', 'Degustação Supra Corp Day'), ('kenvue', 'Ofertas Kenvue'), ('principia', 'Ofertas Principia'), ('botica', 'Ofertas Botica'), ('procter', 'Ofertas Procter'), ('kimberly', 'Ofertas Kimberly'), ('cestoes', 'Cestões'), ('marketing', 'Itens do Marketing')], max_length=20, verbose_name='ação'),
        ),
    ]
