# Generated by Django 6.1.1 on 2026-09-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0002_alter_lancamento_grupo_alter_lancamento_mecanica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='mecanica',
            field=models.CharField(choices=[('leve3', 'Leve 3 Pague 2'), ('supracorp', 'Degustação Supra Corp Day'), ('kenvue', 'Ofertas Kenvue'), ('principia', 'Ofertas Principia'), ('botica', 'Ofertas Botica'), ('procter', 'Ofertas Procter'), ('kimberly', 'Ofertas Kimberly'), ('cestoes', 'Cestões'), ('marketing', 'Itens do Marketing'), ('sellout', 'Sellout Fabricante (referência)')], max_length=20, verbose_name='ação'),
        ),
    ]
