# Generated by Django 6.1.1 on 2026-09-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0001_initial'),
        ('ofertas', '0004_alter_lancamento_mecanica'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['mecanica', 'fabricante'], name='ofertas_lan_mecanic_77b3b8_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['mecanica', 'data'], name='ofertas_lan_mecanic_f91b1a_idx'),
        ),
    ]
