# Generated by Django 6.1.1 on 2026-09-24 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0001_initial'),
        ('ofertas', '0005_lancamento_ofertas_lan_mecanic_77b3b8_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaGeralMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_mes', models.CharField(help_text='formato AAAA-MM', max_length=7, verbose_name='ano-mês')),
                ('itens', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='itens')),
                ('venda', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='venda')),
                ('custo', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='custo')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_gerais_mensais', to='lojas.loja')),
            ],
            options={
                'verbose_name': 'venda geral mensal',
                'verbose_name_plural': 'vendas gerais mensais',
                'indexes': [models.Index(fields=['ano_mes'], name='ofertas_ven_ano_mes_62ddd1_idx')],
                'constraints': [models.UniqueConstraint(fields=('ano_mes', 'loja'), name='venda_geral_unica_por_mes_loja')],
            },
        ),
    ]
