# Generated by Django 6.1.1 on 2026-09-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='código')),
                ('razao_social', models.CharField(max_length=255, verbose_name='razão social')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('cidade', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('bandeira', models.CharField(choices=[('velanes', 'Velanes'), ('ultra_popular', 'Ultra Popular')], default='velanes', max_length=20, verbose_name='bandeira')),
            ],
            options={
                'verbose_name': 'loja',
                'verbose_name_plural': 'lojas',
                'ordering': ['codigo'],
            },
        ),
    ]
