# Generated by Django 6.1.1 on 2026-09-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerbaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mecanica', models.CharField(choices=[('leve3', 'Leve 3 Pague 2'), ('supracorp', 'Degustação Supra Corp Day'), ('kenvue', 'Ofertas Kenvue'), ('principia', 'Ofertas Principia'), ('botica', 'Ofertas Botica'), ('procter', 'Ofertas Procter'), ('kimberly', 'Ofertas Kimberly'), ('cestoes', 'Cestões'), ('marketing', 'Itens do Marketing'), ('sellout', 'Sellout Fabricante (referência)')], max_length=20, verbose_name='mecânica')),
                ('ano_mes', models.CharField(help_text='formato AAAA-MM', max_length=7, verbose_name='ano-mês')),
                ('valor_apurado', models.DecimalField(blank=True, decimal_places=2, help_text='Leve 3: calculado automaticamente. Demais ações: manual, até a fórmula ser definida.', max_digits=14, null=True, verbose_name='valor apurado')),
                ('apuracao_automatica', models.BooleanField(default=False, help_text='True só onde já existe fórmula validada (Leve 3, por ora) — valor_apurado deixa de ser editável no admin.', verbose_name='apuração automática')),
                ('valor_recebido', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='valor recebido')),
                ('data_recebimento', models.DateField(blank=True, null=True, verbose_name='data do recebimento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('recebido', 'Recebido')], default='pendente', max_length=10, verbose_name='status')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'verba mensal',
                'verbose_name_plural': 'verbas mensais',
                'indexes': [models.Index(fields=['mecanica', 'ano_mes'], name='verba_verba_mecanic_17ed8b_idx')],
                'constraints': [models.UniqueConstraint(fields=('mecanica', 'ano_mes'), name='uniq_verba_mecanica_mes')],
            },
        ),
    ]
