# Generated by Django 6.1.1 on 2026-09-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Mesmo texto de "Produto"/"Embalagem" nos relatórios do ERP — chave de cruzamento.', max_length=255, unique=True, verbose_name='descrição')),
                ('codigo_barras', models.CharField(blank=True, max_length=20, verbose_name='código de barras')),
                ('fabricante', models.CharField(max_length=120, verbose_name='fabricante')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos (cadastro)',
                'indexes': [models.Index(fields=['descricao'], name='produtos_pr_descric_7d60b7_idx')],
            },
        ),
    ]
