# Generated by Django 6.1.1 on 2026-09-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RebaixaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mecanica', models.CharField(max_length=20, verbose_name='mecânica')),
                ('campanha', models.CharField(help_text='Mesmo texto de Lancamento.tag_origem (sem o prefixo "Cad. Oferta:") pra casar.', max_length=255, verbose_name='campanha')),
                ('ean', models.CharField(max_length=20, verbose_name='EAN')),
                ('produto_descricao', models.CharField(blank=True, help_text='Guardado pra auditoria e como 2º critério de cruzamento quando o EAN não resolve.', max_length=255, verbose_name='descrição (da planilha do fabricante)')),
                ('valor_rebaixa', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='valor da rebaixa (R$/un.)')),
                ('arquivo_origem', models.CharField(blank=True, max_length=255, verbose_name='arquivo de origem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'rebaixa de produto',
                'verbose_name_plural': 'rebaixas de produto',
                'constraints': [models.UniqueConstraint(fields=('mecanica', 'campanha', 'ean'), name='rebaixa_unica_por_campanha_ean')],
            },
        ),
    ]
